### ISSUE TITLE
Image outside wrapper

### ISSUE THREAD

**Issue by temp0065** [temp0065/mtm6201-midterm#2]
@abhaysharma I want my product cards in mobile size (max-width: 414px) to match the mockup, where the second card cuts off of the wrapper on the right. I tried doing this, but when I do the card just goes outside the wrapper and it doesn't cut off. I also want the images to sit above the padding like in the mockup, but am unsure how to do it without degrouping it from the grid.

**Comment by abhaysharma** [comment]
@temp0065 for having the card cutoff and not have a horizontal scroll you will need to add overflow:hidden to the .wrapper.

For moving the image above the card you can add a negative margin on top of 50px on the .product-image
